NvkLesson07/NvkLesson07/Models/ErrorViewModel.cs
namespace NvkLesson07.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NvkLesson07/NvkLesson07/Models/NvkEmployee.cs
namespace NvkLesson07.Models
{
    public class NvkEmployee
    {
            public int NvkId { get; set; }
            public string NvkName { get; set; }
            public DateTime NvkBirthday { get; set; }
            public string NvkEmail { get; set; }
            public string NvkPhone { get; set; }
            public decimal NvkSalary { get; set; }
            public bool NvkStatus { get; set; } // true = active, false = inactive
        
    }
}

NvkLesson07/NvkLesson07/Controllers/NvkEmployeeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NvkLesson07.Models;

namespace NvkLesson07.Controllers
{
    public class NvkEmployeeController : Controller
    {
        //Mock Data:
        private static List<NvkEmployee> nvkEmployees = new List<NvkEmployee>()
        {
            new NvkEmployee
            {
                NvkId = 1,
                NvkName = "Nguyễn Văn Khánh",
                NvkBirthday = new DateTime(2005 , 5, 29),
                NvkEmail = "khanhvank9t727@gmail.com.com",
                NvkPhone = "0983915173",
                NvkSalary = 15000000,
                NvkStatus = true
            },
            new NvkEmployee
            {
                NvkId = 2,
                NvkName = "Trần Thị B",
                NvkBirthday = new DateTime(2004 , 4 , 16 ),
                NvkEmail = "tranthib@example.com",
                NvkPhone = "0912345678",
                NvkSalary = 18000000,
                NvkStatus = true
            },
            new NvkEmployee
            {
                NvkId = 3,
                NvkName = "Lê Văn C",
                NvkBirthday = new DateTime(2005 , 12, 10),
                NvkEmail = "levanc@example.com",
                NvkPhone = "0934567890",
                NvkSalary = 12000000,
                NvkStatus = false
            },
            new NvkEmployee
            {
                NvkId = 4,
                NvkName = "Phạm Thị D",
                NvkBirthday = new DateTime(2003 , 3, 22),
                NvkEmail = "phamthid@example.com",
                NvkPhone = "0978123456",
                NvkSalary = 20000000,
                NvkStatus = true
            },
            new NvkEmployee
            {
                NvkId = 5,
                NvkName = "Hoàng Văn E",
                NvkBirthday = new DateTime(2004 , 7, 30),
                NvkEmail = "hoangvane@example.com",
                NvkPhone = "0987654321",
                NvkSalary = 22000000,
                NvkStatus = false
            }
        };
        // GET: NvkEmployeeController
        public ActionResult NvkIndex()
        {
            return View(nvkEmployees);
        }

        // GET: NvkEmployeeController/Details/5
        public ActionResult NvkDetail(int id)
        {
            var nvkEmployee = nvkEmployees.FirstOrDefault(x => x.NvkId == id);
            return View(nvkEmployee);
        }

        // GET: NvkEmployeeController/Create
        public ActionResult NvkCreate()
        {
            var nvkEmployee = new NvkEmployee();
            return View(nvkEmployee);
        }

        // POST: NvkEmployeeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NvkCreate(NvkEmployee nvkModel)
        {
            try
            {
                //them moi nhan vien vao list
                nvkModel.NvkId = nvkEmployees.Max(x => x.NvkId) + 1;
                nvkEmployees.Add(nvkModel);
                return RedirectToAction(nameof(NvkIndex));
            }
            catch
            {
                return View();
            }
        }

        // GET: NvkEmployeeController/NvkEdit/5
        public ActionResult NvkEdit(int id)
        {
            var nvkEmployee = nvkEmployees.FirstOrDefault(x => x.NvkId == id);
            return View(nvkEmployee);
        }

        // POST: NvkEmployeeController/NvkEdit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NvkEdit(int id, NvkEmployee nvkModel)
        {
            try
            {
                for (int i = 0; i < nvkEmployees.Count(); i++)
                {
                    if(nvkEmployees[i].NvkId == id)
                    {
                        nvkEmployees[i] = nvkModel;
                        break;
                    }
                }
                return RedirectToAction(nameof(NvkIndex));
            }
            catch
            {
                return View();
            }
        }

        // GET: NvkEmployeeController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: NvkEmployeeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

NvkLesson07/NvkLesson07/Controllers/NvkHomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using NvkLesson07.Models;

namespace NvkLesson07.Controllers
{
    public class NvkHomeController : Controller
    {
        private readonly ILogger<NvkHomeController> _logger;

        public NvkHomeController(ILogger<NvkHomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult NvkIndex()
        {
            return View();
        }

        public IActionResult NvkAbout()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NvkLesson07/NvkLesson07/Views/NvkEmployee/NvkCreate.cshtml
@model NvkLesson07.Models.NvkEmployee

@{
    ViewData["Title"] = "THEM MOI NHAN VIEN";
}

<h1>THEM MOI NHAN VIEN</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="NvkCreate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NvkId" class="control-label"></label>
                <input asp-for="NvkId" class="form-control" />
                <span asp-validation-for="NvkId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NvkName" class="control-label"></label>
                <input asp-for="NvkName" class="form-control" />
                <span asp-validation-for="NvkName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NvkBirthday" class="control-label"></label>
                <input asp-for="NvkBirthday" class="form-control" />
                <span asp-validation-for="NvkBirthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NvkEmail" class="control-label"></label>
                <input asp-for="NvkEmail" class="form-control" />
                <span asp-validation-for="NvkEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NvkPhone" class="control-label"></label>
                <input asp-for="NvkPhone" class="form-control" />
                <span asp-validation-for="NvkPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NvkSalary" class="control-label"></label>
                <input asp-for="NvkSalary" class="form-control" />
                <span asp-validation-for="NvkSalary" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="NvkStatus" /> @Html.DisplayNameFor(model => model.NvkStatus)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="NvkIndex" class="btn btn-secondary">Back to List</a>
</div>

NvkLesson07/NvkLesson07/Views/NvkEmployee/NvkDetail.cshtml
@model NvkLesson07.Models.NvkEmployee

@{
    ViewData["Title"] = "NvkDetail";
}

<h1>NvkDetail</h1>

<div>
    <h4>NvkEmployee</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NvkId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NvkId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NvkName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NvkName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NvkBirthday)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NvkBirthday)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NvkEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NvkEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NvkPhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NvkPhone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NvkSalary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NvkSalary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NvkStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NvkStatus)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="NvkIndex">Back to List</a>
</div>

NvkLesson07/NvkLesson07/Views/NvkEmployee/NvkEdit.cshtml
@model NvkLesson07.Models.NvkEmployee

@{
    ViewData["Title"] = "Chinh sua Thong tin Nhan vien";
}   

<h1>Chinh sua Thong tin Nhan vien</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="NvkEdit" asp-route-id="@Model.NvkId">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NvkId" class="control-label"></label>
                <input asp-for="NvkId" class="form-control" />
                <span asp-validation-for="NvkId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NvkName" class="control-label"></label>
                <input asp-for="NvkName" class="form-control" />
                <span asp-validation-for="NvkName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NvkBirthday" class="control-label"></label>
                <input asp-for="NvkBirthday" class="form-control" />
                <span asp-validation-for="NvkBirthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NvkEmail" class="control-label"></label>
                <input asp-for="NvkEmail" class="form-control" />
                <span asp-validation-for="NvkEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NvkPhone" class="control-label"></label>
                <input asp-for="NvkPhone" class="form-control" />
                <span asp-validation-for="NvkPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NvkSalary" class="control-label"></label>
                <input asp-for="NvkSalary" class="form-control" />
                <span asp-validation-for="NvkSalary" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="NvkStatus" /> @Html.DisplayNameFor(model => model.NvkStatus)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="NvkIndex">Back to List</a>
</div>

NvkLesson07/NvkLesson07/Views/NvkEmployee/NvkIndex.cshtml
@model IEnumerable<NvkLesson07.Models.NvkEmployee>

@{
    ViewData["Title"] = "DANH SACH NHAN VIEN";
}

<h1>DANH SACH NHAN VIEN</h1>

<p>
    <a asp-action="NvkCreate" class="btn btn-primary">Create New</a>
</p>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NvkId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NvkName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NvkBirthday)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NvkEmail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NvkPhone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NvkSalary)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NvkStatus)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NvkId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NvkName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NvkBirthday)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NvkEmail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NvkPhone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NvkSalary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NvkStatus)
            </td>
            <td>
                    @Html.ActionLink("Edit", "NvkEdit", new { id = item.NvkId }) |
                    @Html.ActionLink("Detail", "NvkDetail", new { id = item.NvkId  }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

NvkLesson07/NvkLesson07/Views/NvkHome/NvkIndex.cshtml
@{
    ViewData["Title"] = "Trang Chu";
}

<div class="text-center">
    <h1 class="display-4">Hello, KhanChinTuoi</h1>
    
</div>

NvkLesson07/NvkLesson07/Views/Shared/_NvkLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NvkLesson07</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NvkLesson07.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <partial name="_NvkNavBar" />
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - NvkLesson07 - <a asp-area="" asp-controller="NvkHome" asp-action="NvkAbout">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

NvkLesson07/NvkLesson07/Views/Shared/_NvkNavBar.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="NvkHome" asp-action="NvkIndex">
            NvkLesson07
            <<br />
            Nguyen Van Khanh
            </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="NvkHome" asp-action="NvkIndex">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="NvkHome" asp-action="NvkAbout">Thong tin sinh vien</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="NvkEmployee" asp-action="NvkIndex">Thong tin nhan vien</a>
                </li>
            </ul>
        </div>
    </div>
</nav>